# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='text_html',
            field=models.TextField(default='', verbose_name='Exercise text, rendered as HTML'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='text',
            field=models.TextField(verbose_name='Exercise text, Markdown/LaTeX'),
        ),
    ]
