# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_auto_20170813_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='text_tex',
            field=models.TextField(default='', verbose_name='Exercise text, rendered as LaTeX'),
            preserve_default=False,
        ),
    ]
