# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_auto_20170826_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='license',
            field=models.CharField(choices=[('cc-by', 'CC BY'), ('cc-by-sa', 'CC BY-SA'), ('cc-by-nd', 'CC BY-ND')], default='cc-by', max_length=15),
        ),
    ]
