# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0009_auto_20170829_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exercises.Exercise')),
            ],
        ),
    ]
