# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0011_exerciseexample_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseexample',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
