# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0012_exerciseexample_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='source',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
