# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 16:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercises', '0015_auto_20170925_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='original_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='license',
            field=models.CharField(choices=[('cc-by', 'CC BY'), ('cc-by-sa', 'CC BY-SA')], default='cc-by', max_length=15),
        ),
    ]
