# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0016_auto_20170927_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='source',
        ),
    ]
