# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0017_remove_exercise_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='is_original',
            field=models.BooleanField(default=True),
        ),
    ]
