# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0019_exercise_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
