# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 09:54
from __future__ import unicode_literals

from django.db import migrations
import uuid

def gen_uuid(apps, schema_editor):
    Exercise = apps.get_model('exercises', 'Exercise')
    for row in Exercise.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])

class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0020_exercise_uuid'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
