# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0025_auto_20171005_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
