# configure updates globally
update: False

# configure dependency pinning globally
pin: True

# set the default branch
branch: master

# update schedule
# default: empty
# allowed: "every day", "every week", ..

# search for requirement files
search: True

# Specify requirement files by hand, default is empty
# default: empty
# allowed: list
# requirements:
#   - src/requirements/staging.txt:
#       # update all dependencies and pin them
#       update: all
#       pin: True
#   - requirements/dev.txt:
#       # don't update dependencies, use global 'pin' default
#       update: False
#   - requirements/prod.txt:
#       # update insecure only, pin all
#       update: insecure
#       pin: True

# add a label to pull requests, default is not set
# requires private repo permissions, even on public repos
# default: empty
# label_prs: update

# assign users to pull requests
assignees:
 - flowfx

# configure the branch prefix the bot is using
branch_prefix: pyup/

# set a global prefix for PRs
# default: empty
# pr_prefix: "Bug #12345"

# allow to close stale PRs
close_prs: True
