dist: trusty
language: python
cache: pip
python:
- 3.6
addons:
  chrome: beta
before_install: # Install ChromeDriver
  - wget -N http://chromedriver.storage.googleapis.com/2.31/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
install:
  - sudo apt-get install pandoc
  - npm install markdown-it markdown-it-katex katex
  - pip install -q -r requirements.txt
script:
  - cd src/
  - echo "{}" > secrets.json
  # run Selenium tests
  - pytest system_tests
  # run unit tests with coverage
  - pytest --cov
  - codecov
notifications:
  email: false