dist: trusty
language: python
cache: pip
python:
- 3.6
addons:
  chrome: beta
  ssh_known_hosts: ssh.pythonanywhere.com
before_install:
  # decrypt private deployment key
  - openssl aes-256-cbc -K $encrypted_8feb27c682bd_key -iv $encrypted_8feb27c682bd_iv -in .travis/deploy_key.enc -out .travis/deploy_key -d
  # install chromedriver
  - wget -N http://chromedriver.storage.googleapis.com/2.31/chromedriver_linux64.zip
    -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
install:
  - sudo apt-get install -y texlive-latex-base pandoc
  - npm install markdown-it markdown-it-katex katex
  - pip install -q -r requirements/testing.txt
script:
  - cd src/
  - echo "{}" > secrets.json
  - pytest system_tests
  - pytest --cov
  - codecov
deploy:
  provider: script
  script: .travis/deploy.sh
  on:
    branch: master
notifications:
  email: false
