language: python
cache: pip
python:
- 3.6
install:
  - npm install markdown-it markdown-it-katex katex
  - pip install -r requirements.txt
script:
  - cd src/
  - echo "{}" > secrets.json
  # run unit tests only
  - pytest --cov
  - codecov
notifications:
  email: false