dist: trusty
language: python
cache: pip
python:
- 3.6
services:
  - postgresql
addons:
  chrome: beta
  postgresql: "9.4"
  ssh_known_hosts: ssh.pythonanywhere.com
env:
  global:
    - DB_NAME=travis_ci_test
    - DB_USER=postgres
    - DB_PASSWORD=""
    - DB_HOST=localhost
    - DB_PORT=5432
before_install:
  # create database
  - psql -c 'create database travis_ci_test;' -U postgres
  # decrypt private deployment key
  - openssl aes-256-cbc -K $encrypted_8feb27c682bd_key -iv $encrypted_8feb27c682bd_iv -in .travis/deploy_key.enc -out .travis/deploy_key -d
  # install chromedriver
  - wget -N http://chromedriver.storage.googleapis.com/2.31/chromedriver_linux64.zip
    -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
install:
  - sudo apt-get install -y texlive-latex-extra pandoc
  - pip install -q -r requirements/testing.txt
  - (cd src/ && npm install --production)
script:
  - cd src/
  - echo "{}" > secrets.json
  - python manage.py compress --force
  # - pytest system_tests
  - pytest --cov
  - codecov
after_success:
  - cd ../
  - eval "$(ssh-agent -s)"
  - chmod 600 .travis/deploy_key
  - ssh-add .travis/deploy_key
  - git remote add pythonanywhere flowfx@ssh.pythonanywhere.com:/home/flowfx/bare-repos/unkenmathe.git
  - git push -f pythonanywhere master
  - python .travis/reload-webapp.py
notifications:
  email: false
